name: Docs Sync Check

on:
  push:
    paths:
      - "docs/**"
      - ".github/workflows/docs-sync.yml"
      - "scripts/check-docs-sync.js"

jobs:
  check-sync:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Check docs sync
        run: node scripts/check-docs-sync.js
