name: "Docs Auto Update"

on:
  push:
    paths:
      - "docs/cs/**"
      - "scripts/auto-translate-docs.js"
      - ".github/workflows/docs-auto-update.yml"
      - "package.json"

jobs:
  update-docs:
    if: false # Dočasně vypnuto, dokud nebudou nastaveny Google Cloud credentials
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm ci
      - name: Setup Google Cloud Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: Update translations
        run: node scripts/auto-translate-docs.js
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          GOOGLE_CLOUD_PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
      - name: Commit changes if any
        uses: EndBug/add-and-commit@v9
        with:
          add: "docs/"
          message: "docs: auto update translations"
